# Generated by Django 4.1.7 on 2023-02-28 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Location'},
        ),
    ]
