# Generated by Django 4.1.7 on 2023-02-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='orders',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
