# Generated by Django 4.1.7 on 2023-02-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_customer_orders_employee_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='orders',
        ),
    ]
