# Generated by Django 4.1.7 on 2023-02-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_customer_orders_remove_employee_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('MAN', 'Man'), ('WOMAN', 'Woman'), ('BI', 'Bi'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('MAN', 'Man'), ('WOMAN', 'Woman'), ('BI', 'Bi'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
